### PR TITLE
Adding Artix Linux and Latvian language

### PR DESCRIPTION
**Pull request by kristoferssolo**
- Added support of Latvian language 
- Added Artix Linux icon and way to update grub

### CODE REVIEW

**Comment by shvchk** [comment]
Thank you! Spaces at the end of the line in readme.md are intentional, though : )

**Comment by kristoferssolo** [comment]
Sorry about the white-spaces. I've setup my editor to automatically remove trailing white-spaces and just didn't notice that.
May I know what is the reason behind those spaces, because I still don't get it?

**Comment by shvchk** [comment]
In Markdown, line break in source doesn't create a line break in rendered text, you need either 2 line breaks, but that creates a new paragraph, or 2 trailing spaces before line break to create a simple line break.
See https://www.markdownguide.org/basic-syntax/#line-breaks for details.

**Comment by shvchk** [comment]
Thank you once again, @kristoferssolo :+1:

**Pull request merged**
